const mongoose=require("mongoose");

const CustomerModel=mongoose.Schema({
    Firstname:{
        type:String,
        required:true,
    },
    lastname:{
        type:String,
        required:true,
    },
    MobileNum:{
        type:String,
        required:true
    },
    source:{
        type:String,
        required:true,
        enum:["walk-in","social-media"],
        default:"walk-in"
    },
    MinRange:{
        type:Number,
        required:true,
    },
    MaxRange:{
        type:Number,
        required:true,
    },
    Job:{
        type:String,
        required:true,
    },
    EmployeeID:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Employees",
        required:true
    },
    Address:{
        type:String,
        required:true,
    },
    Street:{
        type:String,
        required:true,
    },
    City:{
        type:String,
        required:true,
    },
    State:{
        type:String,
        required:true,
    },
    Pincode:{
        type:Number,
        required:true,
    },
    CreatedAt:{
        type:Date,
        default:Date.now
    },
    UpdatedAt:{
        type:Date,
        default:Date.now
    }    
});

module.exports=mongoose.model("Customer",CustomerModel); 